// ==============================================================================
//  ELYRIUM RPG: CUSTOM PROGRESSION PORTAL BLOCKS & ARTIFACTS
//  Minecraft 1.21.1 NeoForge | KubeJS Startup Script
// ==============================================================================

StartupEvents.registry('block', event => {
    event.create('infernal_portal_frame')
        .displayName('Обсидиан Преисподней')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(0.25)

    event.create('infernal_portal_frame_active')
        .displayName('Обсидиан Преисподней (Активный)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(1.0)

    event.create('infernal_portal_frame_eye_left')
        .displayName('Око Разлома (Левое)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(1.0)

    event.create('infernal_portal_frame_eye_right')
        .displayName('Око Разлома (Правое)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(1.0)

    // --- Bone Bastion Multiblock Parts ---
    // Corners (Dormant & Active)
    event.create('infernal_portal_corner_dormant')
        .displayName('Костяной Пьедестал (Потухший)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(0.1)

    event.create('infernal_portal_corner_active')
        .displayName('Костяной Пьедестал (Пылающий)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(1.0)

    // Pillars (Dormant & Active)
    event.create('infernal_portal_pillar_dormant')
        .displayName('Рунический Колоннарий (Потухший)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(0.1)

    event.create('infernal_portal_pillar_active')
        .displayName('Рунический Колоннарий (Пылающий)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(1.0)

    event.create('infernal_portal_pillar_left_dormant')
        .displayName('Рунический Колоннарий (Левый, Потухший)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(0.1)

    event.create('infernal_portal_pillar_right_dormant')
        .displayName('Рунический Колоннарий (Правый, Потухший)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(0.1)

    event.create('infernal_portal_pillar_left_active')
        .displayName('Рунический Колоннарий (Левый, Пылающий)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(1.0)

    event.create('infernal_portal_pillar_right_active')
        .displayName('Рунический Колоннарий (Правый, Пылающий)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(1.0)

    // --- 3-Level Tapered Hourglass Pillars (Bottom, Middle, Top) ---
    // Bottom: wide base pedestal (16px), narrows at 40% height to 10px
    event.create('infernal_portal_pillar_bottom_left_dormant').displayName('База Колонны (Левая, Потухшая)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(0.1)
    event.create('infernal_portal_pillar_bottom_right_dormant').displayName('База Колонны (Правая, Потухшая)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(0.1)
    event.create('infernal_portal_pillar_bottom_left_active').displayName('База Колонны (Левая, Пылающая)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(1.0)
    event.create('infernal_portal_pillar_bottom_right_active').displayName('База Колонны (Правая, Пылающая)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(1.0)

    // Middle: narrow waisted column (10px) with shifting runic channel
    event.create('infernal_portal_pillar_middle_left_dormant').displayName('Ствол Колонны (Левый, Потухший)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(0.1)
    event.create('infernal_portal_pillar_middle_right_dormant').displayName('Ствол Колонны (Правый, Потухший)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(0.1)
    event.create('infernal_portal_pillar_middle_left_active').displayName('Ствол Колонны (Левый, Пылающий)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(1.0)
    event.create('infernal_portal_pillar_middle_right_active').displayName('Ствол Колонны (Правый, Пылающий)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(1.0)

    // Top: narrow at bottom (10px), expands at 40% height into wide capital (16px) under corner block
    event.create('infernal_portal_pillar_top_left_dormant').displayName('Капитель Колонны (Левая, Потухшая)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(0.1)
    event.create('infernal_portal_pillar_top_right_dormant').displayName('Капитель Колонны (Правая, Потухшая)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(0.1)
    event.create('infernal_portal_pillar_top_left_active').displayName('Капитель Колонны (Левая, Пылающая)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(1.0)
    event.create('infernal_portal_pillar_top_right_active').displayName('Капитель Колонны (Правая, Пылающая)').soundType('stone').hardness(50.0).resistance(1200.0).requiresTool(true).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_diamond_tool').lightLevel(1.0)

    // Threshold (Dormant & Active - flat, no narrowing)
    event.create('infernal_portal_threshold_dormant')
        .displayName('Порог Врат (Потухший)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(0.1)

    event.create('infernal_portal_threshold_active')
        .displayName('Порог Врат (Пылающий)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(1.0)

    // Keystone Dormant (Left & Right with closed eye)
    event.create('infernal_portal_keystone_left_dormant')
        .displayName('Замковый Свод (Левый, Спящий)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(0.1)

    event.create('infernal_portal_keystone_right_dormant')
        .displayName('Замковый Свод (Правый, Спящий)')
        .soundType('stone')
        .hardness(50.0)
        .resistance(1200.0)
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')
        .tagBlock('minecraft:needs_diamond_tool')
        .lightLevel(0.1)
})

StartupEvents.registry('item', event => {
    // 1. Осколок Сердца Мира (Добывается с элиток, мини-боссов и боссов)
    event.create('world_heart_shard')
        .displayName('§aОсколок Сердца Мира§r')
        .tooltip('§7Фрагмент расколотого первозданного ядра Верхнего Мира.')
        .tooltip('§8Соберите 8 осколков вокруг алмаза, чтобы восстановить Сердце Мира.')
        .rarity('rare')
        .glow(true)
        .maxStackSize(64)

    // 2. Сердце Мира (Собранный катализатор для Обсидиана Преисподней)
    event.create('world_heart')
        .displayName('§6Сердце Мира§r')
        .tooltip('§7Древний реликтовый артефакт, пульсирующий первозданной энергией жизни.')
        .tooltip('§8Используется для пробуждения Обсидиана Преисподней.')
        .rarity('epic')
        .glow(true)
        .maxStackSize(16)

    // 3. Инфернальный Ключ Разлома (Ключ портала в Незер)
    event.create('infernal_igniter')
        .displayName('§6Инфернальный Ключ Разлома§r')
        .tooltip('§7Древний реликтовый ключ из первозданного обсидиана и магмы.')
        .tooltip('§8Пробуждает и запечатывает Инфернальный Портал.')
        .tooltip('§eПКМ по рамке портала: открыть / закрыть разлом.')
        .rarity('epic')
        .unstackable()
        .glow(true)
})
