// Startup script to register unique RPG transition items & scrolls
StartupEvents.registry('item', event => {
    // 1. Сфера Возвышения (Апгрейд ранга / переход на следующий уровень)
    event.create('sphere_of_ascension')
        .displayName('§6Сфера Возвышения§r')
        .tooltip('§7Используется на Кузнечном столе для перековки экипировки на следующий тир.')
        .glow(true)
        .maxStackSize(16)

    // 2. Печать Перерождения (Смена подтипа брони внутри одного ранга: Рыцарь <-> Маг <-> Самурай)
    event.create('sigil_of_transmutation')
        .displayName('§bПечать Перерождения§r')
        .tooltip('§7Позволяет перековать броню в другой классовый сет того же ранга.')
        .glow(false)
        .maxStackSize(16)

    // 3. Эссенция Очищения (Откат брони до базового состояния / возврат в исходный алмаз)
    event.create('essence_of_purification')
        .displayName('§dЭссенция Очищения§r')
        .tooltip('§7Смывает специализированную форму и откатывает сет до чистой базовой основы.')
        .glow(true)
        .maxStackSize(16)

    // 4. Свиток Возвращения в Столицу (Subphase 6.4)
    event.create('town_scroll')
        .displayName('§aСвиток Возвращения§r')
        .tooltip('§7ПКМ для начала 5-секундного ритуала телепортации в Столицу.')
        .tooltip('§cПолучение урона или движение прерывает чтение заклинания.')
        .glow(true)
        .maxStackSize(16)

    // 5. Свиток Экстренного Побега (Subphase 6.4)
    event.create('escape_scroll')
        .displayName('§dСвиток Экстренного Побега§r')
        .tooltip('§7Мгновенный разрыв дистанции на 50 блоков назад.')
        .tooltip('§bДарует Невидимость и Скорость III на 6 секунд.')
        .glow(true)
        .maxStackSize(16)

    // 6. Тировые Артефакты Сброса Характеристик (Tiered Respec Items)
    event.create('respec_shard_copper')
        .displayName('§6Медный Осколок Очищения§r')
        .tooltip('§7Сбрасывает характеристики SimpleStats.')
        .tooltip('§eОграничение: §fУровни героя 1 – 10 (Tier 1–2).')
        .food(f => { f.nutrition(0); f.saturation(0); f.alwaysEdible(); })
        .glow(false)
        .maxStackSize(16)

    event.create('respec_shard_steel')
        .displayName('§bСтальной Осколок Очищения§r')
        .tooltip('§7Сбрасывает характеристики SimpleStats.')
        .tooltip('§eОграничение: §fУровни героя 1 – 20 (Tier 3).')
        .food(f => { f.nutrition(0); f.saturation(0); f.alwaysEdible(); })
        .glow(false)
        .maxStackSize(16)

    event.create('respec_vessel_cinder')
        .displayName('§cПепельный Сосуд Очищения§r')
        .tooltip('§7Сбрасывает характеристики SimpleStats.')
        .tooltip('§eОграничение: §fУровни героя 1 – 30 (Tier 4 Nether).')
        .food(f => { f.nutrition(0); f.saturation(0); f.alwaysEdible(); })
        .glow(true)
        .maxStackSize(16)

    event.create('respec_orb_aether')
        .displayName('§eНебесная Сфера Забвения§r')
        .tooltip('§7Сбрасывает характеристики SimpleStats.')
        .tooltip('§eОграничение: §fУровни героя 1 – 40 (Tier 5 Aether).')
        .food(f => { f.nutrition(0); f.saturation(0); f.alwaysEdible(); })
        .glow(true)
        .maxStackSize(16)

    event.create('respec_echo_void')
        .displayName('§5Эхо Бездны Очищения§r')
        .tooltip('§7Сбрасывает характеристики SimpleStats.')
        .tooltip('§eОграничение: §fУровни героя 1 – 50 (Tier 6 The End).')
        .food(f => { f.nutrition(0); f.saturation(0); f.alwaysEdible(); })
        .glow(true)
        .maxStackSize(16)

    event.create('respec_tome_divine')
        .displayName('§d⭐ Божественный Фолиант Перерождения§r')
        .tooltip('§7Сбрасывает характеристики SimpleStats.')
        .tooltip('§aУниверсальный: §fОчищает душу любого уровня (Tier 7–11).')
        .food(f => { f.nutrition(0); f.saturation(0); f.alwaysEdible(); })
        .glow(true)
        .maxStackSize(16)

    // 7. Походные Бинты Экстренной Помощи (Healing Support)
    event.create('combat_bandage')
        .displayName('§aПоходные Бинты§r')
        .tooltip('§7ПКМ для быстрой перевязки ран в бою.')
        .tooltip('§aВосстанавливает 25% максимального здоровья.')
        .tooltip('§cКулдаун: 45 секунд. Получение урона прерывает наложение.')
        .glow(false)
        .maxStackSize(16)

    // 8. Боевой Рог Провокации (WoW Tank Taunt Engine)
    event.create('war_horn_taunt')
        .displayName('§6Боевой Рог Провокации§r')
        .tooltip('§7Инструмент Танка: ПКМ для устрашающего клича.')
        .tooltip('§eПровоцирует всех врагов в радиусе 14 блоков на 4.0 сек.')
        .tooltip('§bУравнивает вашу угрозу с максимальной в группе +20%.')
        .tooltip('§cКулдаун: 20 секунд. Расходует 25 выносливости.')
        .glow(true)
        .maxStackSize(1)

    // 9. Око Испытаний Колизея (Wave Defense Gate)
    event.create('gate_pearl_colosseum')
        .displayName('§5Око Испытаний Колизея§r')
        .tooltip('§7Используется для открытия Врат Волн на Арене.')
        .tooltip('§eПризывает волны чудовищ ради сундуков с сокровищами.')
        .glow(true)
        .maxStackSize(16)
})
