// Client Script: Filter T1-T3 Weapon Clutter (Wood/Gold variants) from JEI
// NOTE: Items remain in registries so mobs carrying them don't crash or lose weapons!
RecipeViewerEvents.removeEntries('item', event => {
    const HIDDEN_CLUTTER = [
        'simplyswords:wood_longsword',
        'simplyswords:gold_longsword',
        'simplyswords:wood_twinblade',
        'simplyswords:gold_twinblade',
        'simplyswords:wood_rapier',
        'simplyswords:gold_rapier',
        'simplyswords:wood_katana',
        'simplyswords:gold_katana',
        'simplyswords:wood_sai',
        'simplyswords:gold_sai',
        'simplyswords:wood_spear',
        'simplyswords:gold_spear',
        'simplyswords:wood_glaive',
        'simplyswords:gold_glaive',
        'simplyswords:wood_warglaive',
        'simplyswords:gold_warglaive',
        'simplyswords:wood_cutlass',
        'simplyswords:gold_cutlass',
        'simplyswords:wood_claymore',
        'simplyswords:gold_claymore',
        'simplyswords:wood_greathammer',
        'simplyswords:gold_greathammer',
        'simplyswords:wood_greataxe',
        'simplyswords:gold_greataxe',
        'simplyswords:wood_chakram',
        'simplyswords:gold_chakram',
        'simplyswords:wood_scythe',
        'simplyswords:gold_scythe',
        'simplyswords:wood_halberd',
        'simplyswords:gold_halberd',
        'simplyswords:copper_longsword',
        'simplyswords:copper_twinblade',
        'simplyswords:copper_rapier',
        'simplyswords:copper_katana',
        'simplyswords:copper_sai',
        'simplyswords:copper_spear',
        'simplyswords:copper_glaive',
        'simplyswords:copper_warglaive',
        'simplyswords:copper_cutlass',
        'simplyswords:copper_claymore',
        'simplyswords:copper_greathammer',
        'simplyswords:copper_greataxe',
        'simplyswords:copper_chakram',
        'simplyswords:copper_scythe',
        'simplyswords:copper_halberd'
    ]
    HIDDEN_CLUTTER.forEach(id => event.remove(id))
})
