#Hard disable entire modules. Use at your own risk and don't ask for support if you use this
#Fri Aug 29 19:32:44 MSK 2025
farmersdelight=true
backpacked=true
hearth_and_home=true
valhelsia_furniture=true
quark=true
friendsandfoes=true
another_furniture=true
