#Список типов сущностей, для которых будет применяться урезанный урон стрел.
#Примеры: 'minecraft:enderman', 'minecraft:warden'
affectedEntities = ["cataclysm:ancient_remnant", "mowziesmobs:frostmaw"]
#Включить debug-логи для диагностики попаданий стрел
debug = false
#Процент снижения урона от стрел против перечисленных сущностей (0..100). 100 = нет урона
#Range: 0 ~ 100
damageRetainedPercent = 0
#Обход блокирования щитом/фронтальной стойкой (использовать непрямой магический урон)
bypassShield = false
#Пробовать альтернативные источники урона, если основной был заблокирован
useFallbacks = false
#Разрешить финальный фолбэк outOfWorld (очень пробивной тип урона)
allowOutOfWorldFallback = false
#Гарантировать точное списание урона (добавлять недостающий урон после всех редукций)
ensureExactDamage = true

