#Максимальная горизонтальная (XZ) дистанция рендера дождевых партиклов в блоках.
#Range: 0.0 ~ 256.0
rainRenderDistanceXZ = 0.0
#Максимальная высота над игроком (Y) для рендера дождевых партиклов в блоках. Под игроком партиклы всегда рендерятся.
#Range: 0.0 ~ 256.0
rainRenderDistanceY = 0.0
#Включить подробное логирование работы ограничителя дождя (может спамить логи).
debugLogging = true
#Период логирования в тиках (логировать раз в N тиков).
#Range: 1 ~ 2000
debugLogEveryTicks = 20
#Игнорировать DimensionSpecialEffects.renderSnowAndRain (effects) и всегда использовать наш рендер погоды.
forceOverrideEffects = true

