#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 06 12:15:45 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=superDuperVanilla.zip
