#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Oct 01 18:26:11 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=superDuperVanilla.zip
