#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Sep 15 14:38:33 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=superDuperVanilla.zip
