##                          ##
##         BlueMap          ##
##       Core-Config        ##
##                          ##

# By changing the setting (accept-download) below to TRUE you are indicating that you have accepted mojang's EULA (https://account.mojang.com/documents/minecraft_eula),
# you confirm that you own a license to Minecraft (Java Edition)
# and you agree that BlueMap will download and use a minecraft-client file (depending on the minecraft-version) from mojangs servers (https://piston-meta.mojang.com/) for you.
accept-download: true

# The folder where bluemap saves data-files it needs during runtime or to save e.g. the render-progress to resume it later.
data: "bluemap"

# This changes the amount of threads that BlueMap will use to render the maps.
render-thread-count: 2

# Controls whether BlueMap should try to find and load mod-resources and datapacks from the server/world-directories.
scan-for-mod-resources: true

# Disable external metrics
metrics: false

# Config-section for debug-logging
log: {
  file: "bluemap/logs/debug.log"
  append: false
}
