##                          ##
##         BlueMap          ##
##      Plugin-Config       ##
##                          ##

# If the server should send player-positions to the webapp.
# This only works if the integrated webserver is enabled.
live-player-markers: true

# A list of gamemodes that will prevent a player from appearing on the map.
hidden-game-modes: [
	"spectator"
]

# If this is true, players that are vanished (by a plugin) will be hidden on the map.
hide-vanished: true

# If this is true, players that have an invisibility (potion-)effect will be hidden on the map.
hide-invisible: true

# If this is true, players that are sneaking will be hidden on the map.
hide-sneaking: false

# Hides the player if they are in a sky or block-light level below the given number.
hide-below-sky-light: 0
hide-below-block-light: 0

# If this is true, players that are on a different world than the viewed map will not appear on the player-list.
hide-different-world: false

# Download the skin from mojang-servers when a player joins your server, so it can be used for the player-markers.
skin-download: true

# The amount of players that is needed to pause BlueMap's render-threads.
player-render-limit: -1

# The interval in minutes in which a full map-update will be triggered.
full-update-interval: 1440
