##                          ##
##         BlueMap          ##
##     Webserver-Config     ##
##                          ##

# Enable the integrated web-server for admin access
enabled: true

# The webroot that the server will host to the web.
webroot: "bluemap/web"

# The port that the webserver listens to (Admin access port).
port: 8100

# Config-section for webserver-activity logging
log: {
  file: "bluemap/logs/webserver.log"
  append: false
  format: "%1$s \"%3$s %4$s %5$s\" %6$s %7$s"
}
